/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActiveUsersByPlanDto } from '../../models/active-users-by-plan-dto';

export interface ApiReportsActiveUsersByPlanGet$Json$Params {
}

export function apiReportsActiveUsersByPlanGet$Json(http: HttpClient, rootUrl: string, params?: ApiReportsActiveUsersByPlanGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActiveUsersByPlanDto>>> {
  const rb = new RequestBuilder(rootUrl, apiReportsActiveUsersByPlanGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActiveUsersByPlanDto>>;
    })
  );
}

apiReportsActiveUsersByPlanGet$Json.PATH = '/api/Reports/active-users-by-plan';
