/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserInPlanDto } from '../models/user-in-plan-dto';
export interface ActiveUsersByPlanDto {
  planName?: string | null;
  userCount?: number;
  users?: Array<UserInPlanDto> | null;
}
