/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BillingPeriod } from '../models/billing-period';
export interface CreateSubscriptionRequest {
  period?: BillingPeriod;
  planId?: number;
}
