/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PlanDto {
  allowsTrial?: boolean;
  annualPrice?: number;
  features?: Array<string> | null;
  id?: number;
  monthlyPrice?: number;
  name?: string | null;
}
