/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BillingPeriod } from '../models/billing-period';
import { SubscriptionStatus } from '../models/subscription-status';
export interface SubscriptionDetailsDto {
  endDate?: string;
  id?: string;
  period?: BillingPeriod;
  planName?: string | null;
  startDate?: string;
  status?: SubscriptionStatus;
  trialEndDate?: string | null;
}
