/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiPlansGet$Json } from '../fn/plans/api-plans-get-json';
import { ApiPlansGet$Json$Params } from '../fn/plans/api-plans-get-json';
import { apiPlansGet$Plain } from '../fn/plans/api-plans-get-plain';
import { ApiPlansGet$Plain$Params } from '../fn/plans/api-plans-get-plain';
import { PlanDto } from '../models/plan-dto';

@Injectable({ providedIn: 'root' })
export class PlansService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiPlansGet()` */
  static readonly ApiPlansGetPath = '/api/Plans';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlansGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlansGet$Plain$Response(params?: ApiPlansGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlanDto>>> {
    return apiPlansGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlansGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlansGet$Plain(params?: ApiPlansGet$Plain$Params, context?: HttpContext): Observable<Array<PlanDto>> {
    return this.apiPlansGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PlanDto>>): Array<PlanDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPlansGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlansGet$Json$Response(params?: ApiPlansGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlanDto>>> {
    return apiPlansGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPlansGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPlansGet$Json(params?: ApiPlansGet$Json$Params, context?: HttpContext): Observable<Array<PlanDto>> {
    return this.apiPlansGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PlanDto>>): Array<PlanDto> => r.body)
    );
  }

}
